version: "3"

services:
  app:
    image: ghcr.io/hidakatsuya/rails-dev:latest
    command: bash -c 'rm -f tmp/pids/server.pid; bin/rails s -b 0.0.0.0'
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - ${BUNDLE_STORE_PATH:-./tmp/bundle}:/bundle
    environment:
      CHROME_URL: http://chrome:3333
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - '15432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  chrome:
    image: browserless/chrome:1-chrome-stable
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: 600000

volumes:
  pg-data:
