databases:
  - name: shopping_list
    plan: free
    region: singapore
    databaseName: shopping_list
    user: shopping_list

services:
  - type: web
    plan: free
    region: singapore
    name: shopping_list
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopping_list
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
